update parking_lot_core to 0.9
in trying to solve this:

16:52:12     Compiling lock_api v0.4.6
16:52:12  error[E0554]: `#![feature]` may not be used on the stable release channel
16:52:12    --> /Users/builder/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.6/src/lib.rs:93:34
16:52:12     |
16:52:12  93 | #![cfg_attr(feature = "nightly", feature(const_fn_trait_bound))]
16:52:12     |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the attribute
16:52:12     |
16:52:12     = help: the feature `const_fn_trait_bound` has been stable since `1.61.0` and no longer requires an attribute to enable